// IMPORTANT!
// This file has been automatically generated,
// in order to update it's content execute "npm run update"
"use strict"

module.exports = {
    "stylus/at-extend-style": require("./at-extend-style"),
    "stylus/at-rule-empty-line-before": require("./at-rule-empty-line-before"),
    "stylus/at-rule-name-space-after": require("./at-rule-name-space-after"),
    "stylus/at-rule-no-unknown": require("./at-rule-no-unknown"),
    "stylus/block-closing-brace-empty-line-before": require("./block-closing-brace-empty-line-before"),
    "stylus/block-closing-brace-newline-after": require("./block-closing-brace-newline-after"),
    "stylus/block-closing-brace-newline-before": require("./block-closing-brace-newline-before"),
    "stylus/block-closing-brace-space-after": require("./block-closing-brace-space-after"),
    "stylus/block-closing-brace-space-before": require("./block-closing-brace-space-before"),
    "stylus/block-opening-brace-newline-after": require("./block-opening-brace-newline-after"),
    "stylus/block-opening-brace-space-after": require("./block-opening-brace-space-after"),
    "stylus/block-opening-brace-space-before": require("./block-opening-brace-space-before"),
    "stylus/color-hex-case": require("./color-hex-case"),
    "stylus/declaration-colon": require("./declaration-colon"),
    "stylus/hash-object-property-comma": require("./hash-object-property-comma"),
    "stylus/indentation": require("./indentation"),
    "stylus/media-feature-colon": require("./media-feature-colon"),
    "stylus/no-at-require": require("./no-at-require"),
    "stylus/no-eol-whitespace": require("./no-eol-whitespace"),
    "stylus/number-leading-zero": require("./number-leading-zero"),
    "stylus/number-no-trailing-zeros": require("./number-no-trailing-zeros"),
    "stylus/property-no-unknown": require("./property-no-unknown"),
    "stylus/pythonic": require("./pythonic"),
    "stylus/selector-list-comma-newline-after": require("./selector-list-comma-newline-after"),
    "stylus/selector-list-comma-newline-before": require("./selector-list-comma-newline-before"),
    "stylus/selector-list-comma-space-after": require("./selector-list-comma-space-after"),
    "stylus/selector-list-comma-space-before": require("./selector-list-comma-space-before"),
    "stylus/selector-list-comma": require("./selector-list-comma"),
    "stylus/selector-pseudo-class-case": require("./selector-pseudo-class-case"),
    "stylus/selector-type-no-unknown": require("./selector-type-no-unknown"),
    "stylus/semicolon": require("./semicolon"),
    "stylus/single-line-comment-double-slash-space-after": require("./single-line-comment-double-slash-space-after"),
    "stylus/single-line-comment-no-empty": require("./single-line-comment-no-empty"),
    "stylus/single-line-comment": require("./single-line-comment"),
}
